feat css3翻转 鲤鱼 10-28
linshuizhaoying/9537 pull request #6
Opened 2017-10-28 12:11 UTC by 757273750

任务详情：
https://github.com/linshuizhaoying/9537/issues/1#issuecomment-340186041

2017-10-29 12:47 UTC, cinderyx requested changes

2017-10-29 12:47 UTC, cinderyx commented on source/_posts/前端/基础/css/CSS3实现卡片翻转.md
> +title: CSS3实现卡片翻转
`CSS3实现` 改成 `CSS3 实现`

2017-10-29 12:47 UTC, cinderyx commented on source/_posts/前端/基础/css/CSS3实现卡片翻转.md
> +先定一个box，里面放两个div（card），都是绝对定位，然后让其中一个通过transform翻转180度，这样两个card就正反面贴在一起了，最后通过给box的hover效果上，也是用transform翻转180度，这样就是把背面的翻转到前面来了，前面的翻转到后面，实现一个card的翻转。
英文和中文之间需要空格，英文和标点符号之间不需要空格

2017-10-29 12:47 UTC, cinderyx commented on source/_posts/前端/基础/css/CSS3实现卡片翻转.md
> +先定一个box，里面放两个div（card），都是绝对定位，然后让其中一个通过transform翻转180度，这样两个card就正反面贴在一起了，最后通过给box的hover效果上，也是用transform翻转180度，这样就是把背面的翻转到前面来了，前面的翻转到后面，实现一个card的翻转。
数字和中文之间需要空格

2017-10-29 12:47 UTC, cinderyx commented on source/_posts/前端/基础/css/position有几个属性，默认值是什么.md
> +title: position有几个属性，默认值是什么
英文和中文间空格

2017-10-29 12:47 UTC, cinderyx commented on source/_posts/前端/基础/css/position有几个属性，默认值是什么.md
> +## position有几个属性，默认值是什么
英文和中文间空格

2017-10-29 12:47 UTC, cinderyx commented on source/_posts/前端/基础/css/position有几个属性，默认值是什么.md
> +##### css3动画keyframe可以使用哪些属性
英文和中文间空格

2017-10-29 12:47 UTC, cinderyx commented on source/_posts/前端/基础/css/position有几个属性，默认值是什么.md
> +除了static, 其他的都可以使用
英文和中文间空格

2017-11-26 12:42 UTC, linshuizhaoying approved these changes
LGTM

2017-11-26 12:42 UTC, linshuizhaoying commented on source/_posts/前端/基础/css/position有几个属性，默认值是什么.md
> +<script async src="//en.jsrun.net/j3iKp/embed/all/light/"></script>
示例代码未按照之前的来。显示不出来

2017-11-26 12:49 UTC, cinderyx approved these changes
LGTM for Typo

2017-11-26 12:50 UTC, merged